openapi: 3.0.0
info:
  title: dev-docs
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /users:
    get:
      tags:
        - General
      summary: Get Users
      description: This is a call to get all users
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer ${token}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/{uid}:
    get:
      tags:
        - General
      summary: Get Specific User
      description: 'This gets a specific user '
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer ${token}
        - name: uid
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/yeah:
    post:
      tags:
        - General
      summary: This creates a yeah
      description: Create yeahs
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '{}'
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer ${token}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
