name: Markdown File Processor

on:
  push:
    paths:
      - '**.md'

jobs:
  process-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Process Markdown Files
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: node processMarkdown.js
