name: Markdown File Processor

on:
  push:
    paths:
      - '**.md'

jobs:
  process-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Process Markdown Files
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
        run: |
          for file in $(git diff --name-only HEAD HEAD~1 | grep '\.md$'); do
            if [ -f "$file" ]; then
              content=$(cat "$file")
              curl -X POST "$ENDPOINT_URL" \
                -H 'Content-Type: application/json' \
                -H "x-api-key: $API_KEY" \
                -d "{\"content\": \"$content\", \"filepath\": \"$file\"}"
            fi
          done
